### ISSUE TITLE
Missing moveit_task_constructor_msgs/SampleGraspPosesAction.h

### ISSUE THREAD

**Issue by marcpujol-leitat** [ros-planning/moveit_task_constructor#281]
I am trying to follow the moveit tutorials to install Moveit Deep Grasps but compiler fails saying this header is missing.

Is this intended and I need to replace them? 

Thank you!

**Comment by rhaschke** [comment]
Unfortunately, we didn't yet merge #196, which is the basis for the mentioned tutorial. Also, in https://github.com/ros-planning/moveit_task_constructor/pull/196#discussion_r592675803 it was suggested to use an existing action instead of a new one. This essentially replaced `SampleGraspPosesAction` with [`grasping_msgs::GraspPlanningAction`](https://github.com/mikeferguson/grasping_msgs/blob/ros1/action/GraspPlanning.action). So here is what I suggest:
1. Merge #196 into your MTC repo
2. Update the demo to use `grasping_msgs::GraspPlanningAction`
3. Fix all remaining issues.
4. File a PR against https://github.com/PickNikRobotics/deep_grasp_demo and/or https://ros-planning.github.io/moveit_tutorials to incorporate all required changes into the demo/tutorial.

**Comment by rhaschke** [comment]
@qyp-robot: Didn't my suggestion point you in the right direction? If not, please provide a detailed error description (error messages, your environment, etc.)

**Comment by marcpujol-leitat** [comment]
Thank you @rhaschke for fast response! 

I have already merged the PR into my repo and now I am trying to modify the deep_grasp_demo package so it works with the changes.

I am having some troubles with that:
- Inside moveit_task_constructor_(gpd and dexnet) there are header files named grasp_detection.h which create a SimpleActionServer. I understand I need to modify those so they use the GraspPlanningAction. However, GraspPlanningFeedback and Result are missing members that the .cpp is using.
- In the commits of the PR I can see @bostoncleek has also created a class named GraspProvider. Should I be using that inside the deep_pick_and_place.cpp demo, for example in the Generate Grasp Pose stage.

Thanks again!

**Comment by rhaschke** [comment]
I'm afraid I need to forward your questions to @bostoncleek. He implemented all this code originally.

**Comment by bostoncleek** [comment]
You should use GraspProvider in both moveit_task_constructor_(gpd and dexnet) packages. 

You will also need to update the tutorial and demo to use grasping_msgs::GraspPlanningAction. If GraspPlanningFeedback and Result are missing make sure you include the grasping_msgs::GraspPlanningAction action message in you code. Check out the [action lib tutorials](http://wiki.ros.org/actionlib/Tutorials) for help. 

If you have more questions please let me know. I am trying to get permission from my employer to update the demo and tutorial. But if you finish the modifications rhaschke made above please submit a PR and I will review it. 

@marcpujol-leitat

**Comment by marcpujol-leitat** [comment]
Hi,

I have created the PR so you can see the changes I've made.

Thank you!!

**Comment by marcpujol-leitat** [comment]
Hi @qyp-robot,

Now that you have solved the header problems, I think you have to modify the deep_grasp_demo so it works with the changes made in moveit_task_constructor according to the links you have sent.

**Comment by marcpujol-leitat** [comment]
During the changes you made in the moveit_task_constructor, you substituted the original action with GraspPlanningAction which no longer has "grasp_candidates" inside its feedback. You can find there message in the documentation: [Grasp Planning Action](http://docs.ros.org/en/indigo/api/grasping_msgs/html/action/GraspPlanning.html)
As bostoncleek already suggested, if you need help with that, you should check the [Action Lib Tutorials](http://wiki.ros.org/actionlib/Tutorials)

**Comment by marcpujol-leitat** [comment]
Hi @qyp-robot,

If you go to my [Pull Request](https://github.com/PickNikRobotics/deep_grasp_demo/pull/11/files) you will see the changes I made to grasp_detection.cpp.
There you can see what I did to solve what you are mentioning.

However, **it is still not working and I am waiting for bostoncleek to review the changes**, so do not expect it to work propery.

**Comment by marcpujol-leitat** [comment]
Hi @qyp-robot,

This happens when you run moveit_task_constructor_demo demo.launch?

It is working for me. Did you follow the tutorials?

I am using Ubuntu 20.04 and ROS Noetic. In the same workspace I have the moveit_task_constructor I also have the moveit repository (noetic-devel) and panda_moveit_config.

Hope it helps.

**Comment by marcpujol-leitat** [comment]
In my case it runs past where you are stuck and gets stuck somewhere else.

I'm sorry but I don't know how to help you, the only thing I can tell you is to get bostoncleek's fork of moveit_task_constructor instead of the commit you are mentioning:

- [1] git clone https://github.com/ros-planning/moveit_task_constructor.git
- [2] git remote add pr-mtc https://github.com/bostoncleek/moveit_task_constructor
- [3] git fetch pr-mtc
- [4] git merge pr-mtc/pr-deep_grasp_stage

This way you will have the changes he made.

**Comment by marcpujol-leitat** [comment]
Yes, I think we should wait for bostoncleek to review our changes.

Well maybe @rhaschke could help with my issue, as it is a problem regarding the plan function of the class moveit::task_constructor::task

After running the moveit_task_constructor_demo demo.launch and the moveit_task_constructor_gpd gpd_demo.launch, it looks like it is able to create the grasps and select the best ones but gets stuck there, not executing the task.
The command window looks like this:
![image](https://user-images.githubusercontent.com/57673436/125795207-ea712f03-f6ce-4ed7-8723-f4bff4d7a19c.png)

I have checked the code and it gets stuck here, in the task_.plan(max_solutions)
![image](https://user-images.githubusercontent.com/57673436/125795446-abbcaf72-f7fd-4a31-9a0d-996b265bed1f.png)

Where task_ is an object of the class moveit::task_constructor::task.

Do you have any idea of why this may be happening?

Thank you!

**Comment by marcpujol-leitat** [comment]
Hi @qyp-robot,

I can not really help much with that as you are not showing that much information... Maybe you should check the log that the error is pointing at, there you would find more information.

Regarding PCL, I builded version 1.11 after downloading https://github.com/PointCloudLibrary/pcl/archive/pcl-1.11.0.tar.gz 
Usually I do everything with apt-get install but in this case I builded everything (opencv, pcl, moveit) as I was having some troubles with compilation.

**Comment by marcpujol-leitat** [comment]
Hi @qyp-robot

This is explained in the [deep_grasp_demo repository](https://github.com/PickNikRobotics/deep_grasp_demo).

Check point 5 of the GPD Installation.

**Comment by marcpujol-leitat** [comment]
It looks like we have the same problem now... Maybe we need to further modify the moveit_task_constructor_gpd as the planning phase gets stuck somewhere. My understanding of the code is not deep enough to know what to do so I will wait for @bostoncleek to review my repo.

@qyp-robot if you manage to get it working or solve this problem, please keep me updated.

Thanks!

**Comment by Hi-Zed** [comment]
> Yes, I think we should wait for bostoncleek to review our changes.
> 
> Well maybe @rhaschke could help with my issue, as it is a problem regarding the plan function of the class moveit::task_constructor::task
> 
> After running the moveit_task_constructor_demo demo.launch and the moveit_task_constructor_gpd gpd_demo.launch, it looks like it is able to create the grasps and select the best ones but gets stuck there, not executing the task.
> The command window looks like this:
> ![image](https://user-images.githubusercontent.com/57673436/125795207-ea712f03-f6ce-4ed7-8723-f4bff4d7a19c.png)
> 
> I have checked the code and it gets stuck here, in the task_.plan(max_solutions)
> ![image](https://user-images.githubusercontent.com/57673436/125795446-abbcaf72-f7fd-4a31-9a0d-996b265bed1f.png)
> 
> Where task_ is an object of the class moveit::task_constructor::task.
> 
> Do you have any idea of why this may be happening?
> 
> Thank you!

I solved this and managed to run the demo using GPD.

The issue is [https://github.com/bostoncleek/moveit_task_constructor/blob/ae376b6fc703b75bcf41e6d6a46bba0c75b21311/core/src/stages/grasp_provider.cpp#L97](here). In the implementation of the grasp provider.

At line 97 there is a request to lock a mutex, but the same mutex was already locked at line 161. I am not even sure why the mutex is needed, I removed both lines and the demo works like a charm.

**Comment by bostoncleek** [comment]
The GPD demo works now. Update by pulling the latest changes:

1) https://github.com/bostoncleek/deep_grasp_demo/tree/update_generators
2) https://github.com/bostoncleek/moveit_task_constructor/tree/pr-deep_grasp_stage

**Comment by mathieugouletcrvi** [comment]
Hi @bostoncleek I tried to build the demo with the new files from your branch and it seems that the file moveit/utils/moveit_error_code.h is not found in task_p.h . I saw this https://githubmemory.com/repo/ros-planning/moveit_task_constructor/issues/331 from @rhaschke . I tried to merge the branch on the master but I am not still not able to build. 

Is there is a way to find the file or to modify the dependency to build the demo ? 

Thank you.
_________________________________________________________________________________
Errors     << moveit_task_constructor_core:make /home/labcrvi/ws_grasp/logs/moveit_task_constructor_core/build.make.009.log
In file included from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/task_p.h:42:0,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/introspection.cpp:38:
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/task.h:50:10: fatal error: moveit/utils/moveit_error_code.h: No such file or directory
 #include <moveit/utils/moveit_error_code.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by bostoncleek** [comment]
@mathieugouletcrvi You should build the demo using the branch in [PR 14](https://github.com/PickNikRobotics/deep_grasp_demo/pull/14). This is currently working on my end. Please let me know if you experience issues.

**Comment by mathieugouletcrvi** [comment]
@bostoncleek Hi, I restarted with a clean work space for both ws_moveit and ws_grasp and took the branch in PR 14 . 

git clone https://github.com/bostoncleek/moveit_task_constructor.git -b pr-deep_grasp_stage
git clone https://github.com/bostoncleek/deep_grasp_demo.git -b update_generators 

Unfortunatly, I still have a broken dependency from task_p.h on moveit/utils/moveit_error_code.h 

I am on ubuntu 18.04 and ROS melodic running on a virtualbox VM. Is there something else that I should try ?

Thank you

//--------------------------------------------------------------

labcrvi@ubuntu18-vm:~/ws_grasp$ catkin build
-----------------------------------------------------------
Profile:                     default
Extending:        [explicit] /home/labcrvi/ws_moveit/devel
Workspace:                   /home/labcrvi/ws_grasp
-----------------------------------------------------------
Build Space:        [exists] /home/labcrvi/ws_grasp/build
Devel Space:        [exists] /home/labcrvi/ws_grasp/devel
Install Space:      [unused] /home/labcrvi/ws_grasp/install
Log Space:          [exists] /home/labcrvi/ws_grasp/logs
Source Space:       [exists] /home/labcrvi/ws_grasp/src
DESTDIR:            [unused] None
-----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------
[build] Found '9' packages in 0.0 seconds.                                                                               
[build] Package table is up to date.                                                                                     
Starting  >>> moveit_task_constructor_msgs                                                                               
Starting  >>> rviz_marker_tools                                                                                          
Finished  <<< moveit_task_constructor_msgs                         [ 0.9 seconds ]                                       
Finished  <<< rviz_marker_tools                                    [ 1.3 seconds ]                                       
Starting  >>> moveit_task_constructor_core                                                                               
_________________________________________________________________________________________________________________________
Errors     << moveit_task_constructor_core:make /home/labcrvi/ws_grasp/logs/moveit_task_constructor_core/build.make.001.log
In file included from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/task_p.h:42:0,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/introspection.cpp:38:
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/task.h:50:10: fatal error: moveit/utils/moveit_error_code.h: No such file or directory
 #include <moveit/utils/moveit_error_code.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/introspection.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/all] Error 2
make: *** [all] Error 2
cd /home/labcrvi/ws_grasp/build/moveit_task_constructor_core; catkin build --get-env moveit_task_constructor_core | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.........................................................................................................................
Failed     << moveit_task_constructor_core:make                    [ Exited with code 2 ]                                
Failed    <<< moveit_task_constructor_core                         [ 6.1 seconds ]                                       
Abandoned <<< moveit_task_constructor_dexnet                       [ Unrelated job failed ]                              
Abandoned <<< moveit_task_constructor_gpd                          [ Unrelated job failed ]                              
Abandoned <<< deep_grasp_task                                      [ Unrelated job failed ]                              
Abandoned <<< moveit_task_constructor_capabilities                 [ Unrelated job failed ]                              
Abandoned <<< moveit_task_constructor_demo                         [ Unrelated job failed ]                              
Abandoned <<< moveit_task_constructor_visualization                [ Unrelated job failed ]                              
[build] Summary: 2 of 9 packages succeeded.                                                                              
[build]   Ignored:   None.                                                                                               
[build]   Warnings:  None.                                                                                               
[build]   Abandoned: 6 packages were abandoned.                                                                          
[build]   Failed:    1 packages failed.                                                                                  
[build] Runtime: 7.5 seconds total.

**Comment by mathieugouletcrvi** [comment]
@bostoncleek Hi, I restarted with a clean work space for both ws_moveit and ws_grasp and took the branch in 

https://github.com/bostoncleek/deep_grasp_demo/tree/update_generators
https://github.com/bostoncleek/moveit_task_constructor/tree/pr-deep_grasp_stage

Unfortunatly, I still have a broken dependency from task_p.h on moveit/utils/moveit_error_code.h

If I try to take the branch in PR 14 from moveit_task_constructor, there are other build errors. I copied the result at the end of my message.

I am on ubuntu 18.04 and ROS melodic running on a virtualbox VM. Is there something else that I should try ?

Thank you

//--------------------------------------------------------------
-----------------------------------------------------------
Profile:                     default
Extending:        [explicit] /home/labcrvi/ws_moveit/devel
Workspace:                   /home/labcrvi/ws_grasp
-----------------------------------------------------------
Build Space:        [exists] /home/labcrvi/ws_grasp/build
Devel Space:        [exists] /home/labcrvi/ws_grasp/devel
Install Space:      [unused] /home/labcrvi/ws_grasp/install
Log Space:          [exists] /home/labcrvi/ws_grasp/logs
Source Space:       [exists] /home/labcrvi/ws_grasp/src
DESTDIR:            [unused] None
-----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-----------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------
[build] Found '7' packages in 0.0 seconds.                                                              
[build] Updating package table.                                                                         
Starting  >>> moveit_task_constructor_msgs                                                              
Starting  >>> rviz_marker_tools                                                                         
Finished  <<< moveit_task_constructor_msgs                         [ 5.2 seconds ]                      
Finished  <<< rviz_marker_tools                                    [ 11.2 seconds ]                     
Starting  >>> moveit_task_constructor_core                                                              
________________________________________________________________________________________________________
Errors     << moveit_task_constructor_core:make /home/labcrvi/ws_grasp/logs/moveit_task_constructor_core/build.make.002.log
In file included from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/properties.cpp:39:0:
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:211:33: error: ‘vector’ in namespace ‘std’ does not name a template type
  size_t countDefined(const std::vector<std::string>& list) const;
                                 ^~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:211:39: error: expected ‘,’ or ‘...’ before ‘<’ token
  size_t countDefined(const std::vector<std::string>& list) const;
                                       ^
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/properties.cpp:163:8: error: prototype for ‘size_t moveit::task_constructor::PropertyMap::countDefined(const std::vector<std::__cxx11::basic_string<char> >&) const’ does not match any in class ‘moveit::task_constructor::PropertyMap’
 size_t PropertyMap::countDefined(const std::vector<std::string> &list) const
        ^~~~~~~~~~~
In file included from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/properties.cpp:39:0:
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:211:9: error: candidate is: size_t moveit::task_constructor::PropertyMap::countDefined(int) const
  size_t countDefined(const std::vector<std::string>& list) const;
         ^~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/properties.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/storage.h:43:0,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/stage.h:44,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/container.h:41,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/container_p.h:41,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/container.cpp:37:
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:211:33: error: ‘vector’ in namespace ‘std’ does not name a template type
  size_t countDefined(const std::vector<std::string>& list) const;
                                 ^~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:211:39: error: expected ‘,’ or ‘...’ before ‘<’ token
  size_t countDefined(const std::vector<std::string>& list) const;
                                       ^
In file included from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/storage.h:43:0,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/stage.h:44,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/stage_p.h:41,
                 from /home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/introspection.cpp:37:
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:211:33: error: ‘vector’ in namespace ‘std’ does not name a template type
  size_t countDefined(const std::vector<std::string>& list) const;
                                 ^~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/include/moveit/task_constructor/properties.h:211:39: error: expected ‘,’ or ‘...’ before ‘<’ token
  size_t countDefined(const std::vector<std::string>& list) const;
                                       ^
make[2]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/container.cpp.o] Error 1
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/marker_tools.cpp:62:58: error: template-id ‘elements_vector<>’ for ‘const std::vector<std::shared_ptr<urdf::Collision> >& moveit::task_constructor::elements_vector(const urdf::Link&)’ does not match any template declaration
 template <> const std::vector<urdf::CollisionSharedPtr>& elements_vector(const urdf::Link& link) { return link.collision_array; }
                                                          ^~~~~~~~~~~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/marker_tools.cpp:61:61: note: candidate is: template<class T> const std::vector<boost::shared_ptr<X> >& moveit::task_constructor::elements_vector(const urdf::Link&)
 template <class T> const std::vector<boost::shared_ptr<T>>& elements_vector(const urdf::Link& link);
                                                             ^~~~~~~~~~~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/marker_tools.cpp:63:55: error: template-id ‘elements_vector<>’ for ‘const std::vector<std::shared_ptr<urdf::Visual> >& moveit::task_constructor::elements_vector(const urdf::Link&)’ does not match any template declaration
 template <> const std::vector<urdf::VisualSharedPtr>& elements_vector(const urdf::Link& link) { return link.visual_array; }
                                                       ^~~~~~~~~~~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/marker_tools.cpp:61:61: note: candidate is: template<class T> const std::vector<boost::shared_ptr<X> >& moveit::task_constructor::elements_vector(const urdf::Link&)
 template <class T> const std::vector<boost::shared_ptr<T>>& elements_vector(const urdf::Link& link);
                                                             ^~~~~~~~~~~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/marker_tools.cpp:66:45: error: template-id ‘element<>’ for ‘const CollisionSharedPtr& moveit::task_constructor::element(const urdf::Link&)’ does not match any template declaration
 template <> const urdf::CollisionSharedPtr& element(const urdf::Link& link) { return link.collision; }
                                             ^~~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/marker_tools.cpp:65:48: note: candidate is: template<class T> const boost::shared_ptr<X>& moveit::task_constructor::element(const urdf::Link&)
 template <class T> const boost::shared_ptr<T>& element(const urdf::Link& link);
                                                ^~~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/marker_tools.cpp:67:42: error: template-id ‘element<>’ for ‘const VisualSharedPtr& moveit::task_constructor::element(const urdf::Link&)’ does not match any template declaration
 template <> const urdf::VisualSharedPtr& element(const urdf::Link& link) { return link.visual; }
                                          ^~~~~~~
/home/labcrvi/ws_grasp/src/moveit_task_constructor/core/src/marker_tools.cpp:65:48: note: candidate is: template<class T> const boost::shared_ptr<X>& moveit::task_constructor::element(const urdf::Link&)
 template <class T> const boost::shared_ptr<T>& element(const urdf::Link& link);
                                                ^~~~~~~
make[2]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/marker_tools.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/introspection.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/moveit_task_constructor_core.dir/all] Error 2
make: *** [all] Error 2
cd /home/labcrvi/ws_grasp/build/moveit_task_constructor_core; catkin build --get-env moveit_task_constructor_core | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
........................................................................................................
Failed     << moveit_task_constructor_core:make                    [ Exited with code 2 ]               
Failed    <<< moveit_task_constructor_core                         [ 15.2 seconds ]                     
Abandoned <<< moveit_task_constructor_dexnet                       [ Unrelated job failed ]             
Abandoned <<< moveit_task_constructor_gpd                          [ Unrelated job failed ]             
Abandoned <<< deep_grasp_task                                      [ Unrelated job failed ]             
Abandoned <<< moveit_task_constructor_visualization                [ Unrelated job failed ]             
[build] Summary: 2 of 7 packages succeeded.                                                             
[build]   Ignored:   None.                                                                              
[build]   Warnings:  None.                                                                              
[build]   Abandoned: 4 packages were abandoned.                                                         
[build]   Failed:    1 packages failed.                                                                 
[build] Runtime: 26.5 seconds total.

**Comment by rhaschke** [comment]
@mathieugouletcrvi, did you update your MoveIt installation? We have cut a new release into MoveIt (1.0.9) recently, which is not yet synced. Consider using the debians from the [ROS `testing` repo](http://wiki.ros.org/TestingRepository).

**Comment by mathieugouletcrvi** [comment]
@rhaschke Hi, I tried to use ROS testing repo. It still does not work... If I go with the master branch, I have error including SampleGraspPosesAction.h in grasp_image_detection.cpp and grasp_detection.h. The other error is still moveit_error_code.h missing from task.h.

@bostoncleek Hi, If I use the testing repo with the PR14 branch, I still miss moveit_error_code.h in task.h. I found the file here : https://docs.ros.org/en/api/moveit_core/html/cpp/moveit__error__code_8h_source.html and pasted it in the same directory as task.h, changing the path to #include "moveit_error_code.h" With this, I am able to build all the package, but with this message 

[build] An internal error occurred!                                                                                             
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 549, in build_isolated_workspace
    continue_without_deps=False))
  File "/usr/lib/python2.7/dist-packages/catkin_tools/execution/executor.py", line 374, in run_until_complete
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python2.7/dist-packages/trollius/base_events.py", line 350, in run_until_complete
    return future.result()
  File "/usr/lib/python2.7/dist-packages/trollius/futures.py", line 285, in result
    compat.reraise(type(self._exception), self._exception, exc_tb)
  File "/usr/lib/python2.7/dist-packages/trollius/tasks.py", line 259, in _step
    result = coro.send(value)
  File "/usr/lib/python2.7/dist-packages/trollius/tasks.py", line 387, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.

If I still try to run the demo, roslaunch moveit_task_constructor_demo demo.launch launch rviz with the panda robot with thie error 

[ INFO] [1643136263.170738920]: Using planning interface 'OMPL'
[ERROR] [1643136263.176365833]: Exception while loading planning adapter plugin 'default_planner_request_adapters/ResolveConstraintFrames': According to the loaded plugin descriptions the class default_planner_request_adapters/ResolveConstraintFrames with base class type planning_request_adapter::PlanningRequestAdapter does not exist. Declared types are  default_planner_request_adapters/AddIterativeSplineParameterization default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/AddTimeParameterization default_planner_request_adapters/Empty default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints default_planner_request_adapters/FixWorkspaceBounds

If I try roslaunch moveit_task_constructor_gpd gpd_demo.launch . It does not work  and gives this error message 

ERROR: cannot launch node of type [deep_grasp_task/deep_grasp_demo]: Cannot locate node of type [deep_grasp_demo] in package [deep_grasp_task]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [moveit_task_constructor_gpd/grasp_cloud_detection]: Cannot locate node of type [grasp_cloud_detection] in package [moveit_task_constructor_gpd]. Make sure file exists in package path and permission is set to executable (chmod +x)

It is the same for roslaunch moveit_task_constructor_dexnet dexnet_demo.launch

ERROR: cannot launch node of type [deep_grasp_task/deep_grasp_demo]: Cannot locate node of type [deep_grasp_demo] in package [deep_grasp_task]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [moveit_task_constructor_dexnet/grasp_image_detection]: Cannot locate node of type [grasp_image_detection] in package [moveit_task_constructor_dexnet]. Make sure file exists in package path and permission is set to executable (chmod +x)

I will try on with noetic to see if I get the same result. 

Thank you.

**Comment by mathieugouletcrvi** [comment]
Hi @qyp-robot which branches have you used when you said : I have completed the linkage of panda robot model between moveit and gazebo.

Is it :
https://github.com/bostoncleek/deep_grasp_demo.git -b update_generators
https://github.com/bostoncleek/moveit_task_constructor.git -b pr-deep_grasp_stage

And
https://github.com/ros-planning/panda_moveit_config.git -b melodic-devel  
Or 
https://github.com/ros-planning/panda_moveit_config.git -b noetic-devel
And
https://github.com/tahsinkose/franka_ros.git -b melodic-devel  
Or  
https://github.com/frankaemika/franka_ros/tree/melodic-devel -b melodic-devel

Or have you used the setup assistant to generate the panda_moveit_config ?
Did you have to modify the files to make the robot follow rviz in gazebo ?

I opened this issue to discuss the topic :
https://github.com/PickNikRobotics/deep_grasp_demo/issues/15

The best I have done so far was to operate the panda robot in rviz only, with dexnet and gpd, but the robot is still falling under gravity in gazebo and does not moved. Any help would be greatly appreciated.
